Films.Web/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Films.BLL.Services;
using Films.DAL.Model;
using Films.Web.Models;
using System.IO;
using PagedList;

namespace Films.Web.Controllers
{
    [Authorize]
    public class FilmsController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ReturnToList()
        {
            TempData["PageIndexFromSession"] = true;
            return RedirectToAction("Index");
        }
                
        public ActionResult FilmsList(int pageIndex)
        {
            if (TempData["PageIndexFromSession"] != null)
                if (Session["FilmsList_PageIndex"] != null)
                {
                    pageIndex = Convert.ToInt32(Session["FilmsList_PageIndex"]);
                    TempData["PageIndexFromSession"] = null;
                }

            List<MovieListItemModel> model = new List<MovieListItemModel>();
            using (IMovieService service = new MovieService())
            {
                List<Movie> itemList = service.GetList().ToList();
                itemList.ForEach(x => model.Add(new MovieListItemModel(x)));
            }

            Session["FilmsList_PageIndex"] = pageIndex;

            return View(model.ToPagedList(pageIndex, Constants.PAGE_SIZE));
        }

        public ActionResult Edit(int? ID)
        {
            MovieEditModel model;
            if (ID.HasValue)
            {
                using (IMovieService service = new MovieService())
                {
                    model = new MovieEditModel(service.GetMovieById(ID.Value));
                    if (model.UserId != CurrentUserId)
                        return new HttpNotFoundResult("Not found!");
                }
            }
            else
                model = new MovieEditModel();

            return View(model);
        }


        [HttpPost]
        public ActionResult Edit(MovieEditModel model, HttpPostedFileBase PosterFile)
        {
            if (!ModelState.IsValid)
            {
                ShowAlert(AlertType.Error, GetModelErrors());
                return View(model);
            }
            
            if (!model.IsEdit)
                if ((PosterFile == null) || (PosterFile.ContentLength == 0))
                {
                    ShowAlert(AlertType.Error, "Poster file is required");
                    return View(model);
                }

            using (IMovieService service = new MovieService())
            {
                Movie dbItem = new Movie();
                if (model.IsEdit)
                {
                    dbItem = service.GetMovieById(model.MovieId);
                }
                else
                {
                    dbItem.UserId = CurrentUserId;
                }

                dbItem.MovieName = model.MovieName;
                dbItem.Director = model.Director;
                dbItem.Description = model.Description;
                dbItem.MovieYear = model.MovieYear;

                if ((PosterFile != null) && (PosterFile.ContentLength != 0))
                    using (var binaryReader = new BinaryReader(PosterFile.InputStream))
                    {
                        dbItem.Poster = binaryReader.ReadBytes(PosterFile.ContentLength);
                    }
                
                if (model.MovieId > 0)
                    service.Update(dbItem);
                else
                    service.Add(dbItem);

            }

            return RedirectToAction("ReturnToList");

        }

        public ActionResult Delete(int id)
        {
            using (IMovieService service = new MovieService())
            {
                if (service.GetMovieById(id).UserId != CurrentUserId)
                    return new HttpNotFoundResult("Not found!");

                service.Delete(id);
            }
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Info(int ID)
        {
            MovieEditModel model;
            
                using (IMovieService service = new MovieService())
                {
                    Movie dbItem = service.GetMovieById(ID);
                    if (dbItem == null)
                        return new HttpNotFoundResult("Not found!");

                    model = new MovieEditModel(dbItem);
                }

            return View(model);
        }

    }
}

Films.Web/Views/Films/Edit.cshtml
@using Films.Web;
@model Films.Web.Models.MovieEditModel
@{
    ViewBag.Title = "Films :: Movie Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section TitleContent{@ViewBag.Title}

<style type="text/css">
    .poster_img {
        float:left;
        width:200px;
        margin-left:15px;
    }
</style>

<div>
    @using (Html.BeginForm("Edit", "Films", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal form-horizontal-2" }))
    {
        @Html.AntiForgeryToken()

        const string inputCss = "form-control";
        const string divCss = "col-sm-4";

        @Html.HiddenFor(m => m.MovieId)

        <div class="form-group">
            @Html.LabelFor(m => m.MovieName, new { @class = "control-label" })
            <div class="@divCss">
                @Html.TextBoxFor(m => m.MovieName, new { @class = @inputCss })
                @Html.ValidationMessageFor(m => m.MovieName)
            </div>
        </div>
        
        if (Model.IsEdit)
        {
            <div class="form-group">
                @Html.LabelFor(m => m.Poster, new { @class = "control-label" })
                <img alt="Poster" src="@Model.PosterUrl" class="poster_img"/>
            </div>
            <div class="form-group">
                @Html.Label("New poster (if needed)", new { @class = "control-label" })
                <div class="@divCss">
                    <input type="file" name="PosterFile" id="PosterFile" style="margin-top:8px;" />
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                @Html.LabelFor(m => m.Poster, new { @class = "control-label" })
                <div class="@divCss">
                    <input type="file" name="PosterFile" id="PosterFile" style="margin-top:8px;"/>
                </div>
            </div>
        }
        
        <div class="form-group">
            @Html.LabelFor(m => m.MovieYear, new { @class = "control-label" })
            <div class="@divCss">
                @Html.DropDownListFor(m => m.MovieYear, Model.YearDDList, new { @class = @inputCss })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { @class = "control-label" })
            <div class="@divCss">
                @Html.TextAreaFor(m => m.Description, new { @class = @inputCss })
                @Html.ValidationMessageFor(m => m.Description)
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(m => m.Director, new { @class = "control-label" })
            <div class="@divCss">
                @Html.TextBoxFor(m => m.Director, new { @class = @inputCss })
                @Html.ValidationMessageFor(m => m.Director)
            </div>
        </div>
        
        <div class="form-group">
            <div class="actions">
                <button class="btn btn-primary" type="submit" id="btnSave">Save</button>
                <a class="btn btn-default" href="@Url.Action("ReturnToList")">Cancel</a>
            </div>
        </div>
        
    }
</div>

@section styles
{
    
}

@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {

        });
    </script>
}

Films.Web/Views/Films/FilmsList.cshtml
@using MvcContrib.UI.Grid
@using Films.Web;
@using Films.Web.Models;
@using Films.Web.Security;
@using PagedList.Mvc
@model PagedList.IPagedList<MovieListItemModel>

@{
    Layout = null;
}

<style type="text/css">
    .poster_img {
        float:left;
        width:200px;
        margin-right:10px;
    }

    .container {
        background: #ffffff none repeat scroll 0% 0%;
        border: 1px solid #D4D4D4;
        box-shadow: 0px 0px 4px #DBDBDB;
        margin-top: 15px;
        margin-bottom: 5px;
        margin-left: 0px;
        margin-right: 0px;
        padding-bottom: 10px;
    }

    .not_found {
        margin-top: 15px;
    }

    .info .type {
        color: #f60;
        padding-left: 23px;
    }

    .info td {
        min-height: 14px;
        vertical-align: top;
        padding: 6px 0 6px 20px;
        color: #555;
    }

    .lnk_fa_action
    {
        
    }

</style>

    @{
        if (Model.Any())
        {
            foreach(MovieListItemModel item in Model)
            {
      
                <div class="container">
                    <h4>
                        @if (item.UserId == UserPrincipal.Current.UserId)
                        {
                        <a class="lnk_fa_action" href="@Url.Action("Edit", "Films", new { ID = item.MovieId })" title="Edit">
                            <i class="fa fa-pencil fa-action"></i>
                        </a>
                        <a class="lnk_fa_action" href="javascript:void(0);"  onclick="if (confirm('Are you sure you want to delete this film?')) { DeleteFilm(@(item.MovieId)) }" title="Delete">
                            <i class="fa fa-trash-o fa-action"></i>
                        </a>
                        }
                        <a href="@Url.Action("Info", "Films", new { ID = item.MovieId })" title="">@item.MovieName</a>
                    </h4>
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-12">
                            <a href="@Url.Action("Info", "Films", new { ID = item.MovieId })" title="">
                                <img alt="Poster" src="@item.PosterUrl" class="poster_img"/>
                            </a>
                            <div>
                                <table class="info">
                                    <tbody>
                                    <tr>
                                        <td class="type">Year</td>
                                        <td>
                                            @item.MovieYear.ToString()
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="type">
                                            Description
                                        </td>
                                        <td>
                                            @item.Description
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="type">
                                            Director
                                        </td>
                                        <td>
                                            @item.Director
                                        </td>
                                    </tr>
                                    
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            }
                
            @Html.PagedListPager(Model, page => "javascript:GetFilmsList(" + page.ToString() + ");")
        }
        else
        {
            <div class="not_found">
                <strong>No films found</strong>
            </div>
        }
        @Html.Hidden("FilmsListPageNumber", Model.PageNumber.ToString())
    }

<script type="text/javascript">
    $(document).ready(function () {
        
    });
</script>

Films.Web/Views/Films/Index.cshtml
@using Films.Web;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Films :: List";
}

@section TitleContent{@ViewBag.Title}

@section styles
{
    <style type="text/css">
    </style>
}

<div>
    <a class="btn btn-large btn-primary" href="@Url.Action("Edit", "Films", null)">Add Movie</a>
</div>
<div id="films-list" class="table_container">
    
</div>

<script type="text/javascript">
    $(function () {
        GetFilmsList(1);
	});

	function GetFilmsList(pageIndex) {
	    if (isNaN(pageIndex) || (pageIndex == 0)) {
	        pageIndex = $("#FilmsListPageNumber").val()
	    }

	    $.get("@Url.Action("FilmsList")",
				{
				    pageIndex: pageIndex
				},
                function (result) {
                    $("#films-list").html(result);
                });
	}

    function DeleteFilm(id) {
        $.ajax({
            url: "@Url.Action("Delete")",
            cache: false,
            data: {
                id: id
            },
            success: function (result) {
                GetFilmsList(0);
            }
        });
    }
</script>

Films.Web/Views/Films/Info.cshtml
@using Films.Web;
@model Films.Web.Models.MovieEditModel
@{
    ViewBag.Title = "Films :: Movie View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section TitleContent{@ViewBag.Title}

<style type="text/css">
    .poster_img {
        float:left;
        width:200px;
        margin-left:15px;
    }
</style>

<div class="form-horizontal form-horizontal-2">
    @{
        const string inputCss = "form-control";
        const string divCss = "col-sm-4";
    }

    @Html.HiddenFor(m => m.MovieId)

    <div class="form-group">
        @Html.LabelFor(m => m.MovieName, new { @class = "control-label" })
        <div class="@divCss">
            <p class="data-label">@Model.MovieName</p>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Poster, new { @class = "control-label" })
        <img alt="Poster" src="@Model.PosterUrl" class="poster_img"/>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(m => m.MovieYear, new { @class = "control-label" })
        <div class="@divCss">
            <p class="data-label">@Model.MovieYear.ToString()</p>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "control-label" })
        <div class="@divCss">
            <p class="data-label">@Model.Description</p>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Director, new { @class = "control-label" })
        <div class="@divCss">
            <p class="data-label">@Model.Director</p>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.UserName, new { @class = "control-label" })
        <div class="@divCss">
            <p class="data-label">@Model.UserName</p>
        </div>
    </div>

    <div class="form-group">
        <div class="actions">
            <a class="btn btn-default" href="@Url.Action("ReturnToList")">Back To List</a>
        </div>
    </div>
    
</div>

@section styles
{
    
}

@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {

        });
    </script>
}